### PR TITLE
Update 02_useR_groups_asia.Rmd

### PR DESCRIPTION
**Pull request by whitelog**
Would you mind me of appending the 51-54 lines to add user group from South Korea?

### CODE REVIEW

**Comment by csgillespie** [comment]
Thanks. Would you change the "South Korea" in the bullet point to the city name?

**Comment by whitelog** [comment]
Indeed, there exist a one overall and explicit community(R Korea) including the two separates in South Korea, so I omit the city name.

**Comment by csgillespie** [comment]
OK, but where do the groups meet? KRUG looks like it meets in Seoul?

**Comment by whitelog** [comment]
Seoul, Kyunggi, Jeju and etc. You can refer to following link. 
http://event.r-kor.org/
http://ruck2016.r-kor.org

**Comment by csgillespie** [comment]
So to be clear, the groups meet in different locations around South Korea?

**Comment by whitelog** [comment]
Yes! That's it!

**Comment by whitelog** [comment]
Thank you so much!

**Pull request merged**
