### PR TITLE
add UQ RUG in brisbane

### PR DESCRIPTION
**Pull request by orchid00**

### CODE REVIEW

**Comment by csgillespie** [comment]
@orchid00 The link to meet-up doesn't work.

**Comment by orchid00** [comment]
https://twitter.com/UQ_RUG this is the URL I've added

**Comment by csgillespie** [comment]
@orchid00 But the link (https://www.meetup.com/Brisbane-Users-of-R-Group-BURGr/events/) doesn't work for me

**Comment by orchid00** [comment]
I don't manage that meetup, maybe it went obsolete. let me know what you need to add the UQ RUG link please

**Comment by csgillespie** [comment]
@orchid00 Ahh, I understand. I've removed the link to meet-up and replaced with twitter.

Do you not have a home page for the meet-up?

**Comment by orchid00** [comment]
Hi @csgillespie the BurgR is a group I know of, I joined them once, but do not coordinate. So I don't know of their plans or sustainability, as far as I know it stopped working two years ago. You might as well remove it, but that's up to page maintainers.

I was just adding to this file that in Brisbane we have a UQ RUG which is for the university of Queensland I co-founded that UQ RUG last year, so far we only have a twitter account.

**Comment by csgillespie** [comment]
@orchid00 So I think I get it now.

1. I've removed Brisbane as it seems dead.
2. Your proposed group doesn't have a web page or details, so I won't add this group just now. If you create a landing page for your group, then feel free to make another PR.

Thanks!

**Pull request merged**
